[package]
name = "gemfile_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
gzip = "0.1.2"
reqwest = "0.12.9"
tar = "0.4.43"
tokio = {version =  "1.42.0", features = ["full"]}